[alias]
# Using `--features=full --features=nightly` instead of `--all-features` because of
# https://github.com/rust-lang/cargo/issues/10333
#
# "tokio/macros" and "tokio/rt-multi-thread" are required for examples
docs = """doc
-Zrustdoc-scrape-examples
--features=full --features=nightly
--features=tokio/macros --features=tokio/rt-multi-thread
"""

[build]
# We pass "--cfg docsrs" when building docs to add `This is supported on feature="..." only.`
rustdocflags = ["--cfg", "docsrs", "-Znormalize-docs"]
